apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-tests
spec:
  template:
    spec:
      containers:
        - name: playwright
          image: ghcr.io/sachinkp09/playwright-tests:latest
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 0